workspace:
  base: /go
  path: src/github.com/drone/drone-exec

pipeline:
  build:
    image: golang:1.6.2-alpine
    commands:
      - go test github.com/drone/drone-exec/agent/...
      - go test github.com/drone/drone-exec/build/...
      - go test github.com/drone/drone-exec/yaml/...
      - go build

  publish:
    image: docker
    repo: drone/agent
    tags: [ "latest", "0.5.0", "0.5" ]
    storage_driver: overlay
    when:
      event: push
      branch: master
