clone:
  path: github.com/drone/drone-exec

build:
  image: golang:1.5
  environment:
    - GOPATH=/drone
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
  commands:
    - go get github.com/franela/goblin
    - go get ./...
    - go test ./...
    - go build

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: teaci/drone-exec
    tag: [ "testing", "0.4.2.5" ]
    when:
      repo: TeaCI/drone-exec
      branch: [ "master", "0.4.2.5" ]
